#!/usr/bin/env bash
set -euo pipefail

APP_DIR=""
ENV_FILE=""
SERVICE_MANAGER=""
SERVICE_NAME="beacyn"
PLIST_LABEL=""
PLIST_FILE=""
LOG_FILE=""
ERROR_LOG_FILE=""
FRONTEND_URL=""
BACKEND_URL=""
FRONTEND_PORT="7145"
BACKEND_PORT="5145"
NPM_BIN="npm"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --app-dir) APP_DIR="$2"; shift ;;
    --env-file) ENV_FILE="$2"; shift ;;
    --service-manager) SERVICE_MANAGER="$2"; shift ;;
    --service-name) SERVICE_NAME="$2"; shift ;;
    --plist-label) PLIST_LABEL="$2"; shift ;;
    --plist-file) PLIST_FILE="$2"; shift ;;
    --log-file) LOG_FILE="$2"; shift ;;
    --error-log-file) ERROR_LOG_FILE="$2"; shift ;;
    --frontend-url) FRONTEND_URL="$2"; shift ;;
    --backend-url) BACKEND_URL="$2"; shift ;;
    --frontend-port) FRONTEND_PORT="$2"; shift ;;
    --backend-port) BACKEND_PORT="$2"; shift ;;
    --npm-bin) NPM_BIN="$2"; shift ;;
    *) echo "Unknown argument: $1" >&2; exit 1 ;;
  esac
  shift
done

[[ -n "$APP_DIR" ]] || { echo "Missing --app-dir" >&2; exit 1; }
[[ -n "$ENV_FILE" ]] || { echo "Missing --env-file" >&2; exit 1; }
[[ -n "$SERVICE_MANAGER" ]] || { echo "Missing --service-manager" >&2; exit 1; }

CLI_SOURCE="$APP_DIR/src/scripts/beacynctl.sh"
CLI_DIR="$APP_DIR/bin"
CLI_PATH="$CLI_DIR/beacynctl"
CLI_CONFIG="$APP_DIR/.beacynctl.env"
CLI_CMD_FILE="$APP_DIR/.beacynctl-command"
PID_FILE="$APP_DIR/.beacyn.pid"

[[ -f "$CLI_SOURCE" ]] || { echo "beacynctl source not found: $CLI_SOURCE" >&2; exit 1; }

mkdir -p "$CLI_DIR"
cp "$CLI_SOURCE" "$CLI_PATH"
chmod +x "$CLI_PATH"

cat > "$CLI_CONFIG" <<EOF
# Generated by install-beacynctl.sh
APP_DIR=$APP_DIR
ENV_FILE=$ENV_FILE
SERVICE_MANAGER=$SERVICE_MANAGER
SERVICE_NAME=$SERVICE_NAME
PLIST_LABEL=$PLIST_LABEL
PLIST_FILE=$PLIST_FILE
LOG_FILE=$LOG_FILE
ERROR_LOG_FILE=$ERROR_LOG_FILE
PID_FILE=$PID_FILE
FRONTEND_URL=$FRONTEND_URL
BACKEND_URL=$BACKEND_URL
FRONTEND_PORT=$FRONTEND_PORT
BACKEND_PORT=$BACKEND_PORT
NPM_BIN=$NPM_BIN
EOF
chmod 600 "$CLI_CONFIG"

BEACYN_CTL_LINK=""
if [[ -w /usr/local/bin ]] || { [[ ! -e /usr/local/bin ]] && [[ -w /usr/local ]]; }; then
  mkdir -p /usr/local/bin
  ln -sf "$CLI_PATH" /usr/local/bin/beacynctl
  BEACYN_CTL_LINK="/usr/local/bin/beacynctl"
elif [[ -w "$HOME/.local/bin" ]] || { [[ ! -e "$HOME/.local/bin" ]] && [[ -w "$HOME" ]]; }; then
  mkdir -p "$HOME/.local/bin"
  ln -sf "$CLI_PATH" "$HOME/.local/bin/beacynctl"
  BEACYN_CTL_LINK="$HOME/.local/bin/beacynctl"
fi

BEACYN_CTL_CMD="${CLI_PATH/#$HOME/~}"
if [[ -n "$BEACYN_CTL_LINK" ]]; then
  case ":$PATH:" in
    *":$(dirname "$BEACYN_CTL_LINK"):"*) BEACYN_CTL_CMD="beacynctl" ;;
    *) BEACYN_CTL_CMD="${BEACYN_CTL_LINK/#$HOME/~}" ;;
  esac
fi

echo "$BEACYN_CTL_CMD" > "$CLI_CMD_FILE"
