worker_processes auto;

events {
  worker_connections 1024;
}

http {
  include /etc/nginx/mime.types;
  default_type application/octet-stream;
  server_tokens off;

  sendfile on;
  keepalive_timeout 65;

  upstream beacyn_backend {
    server app:5145;
  }

  upstream beacyn_frontend {
    server app:7145;
  }

  server {
    listen 80;
    server_name _;

    proxy_buffers 8 16k;
    proxy_buffer_size 32k;
    client_max_body_size 50m;

    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;

    location /api/ {
      proxy_pass http://beacyn_backend;
    }

    location /health {
      proxy_pass http://beacyn_backend/health;
    }

    location / {
      proxy_pass http://beacyn_frontend;
    }
  }
}
